package shardctrler

import (
	"github.com/hanzug/RaftKV/labrpc"
	"github.com/hanzug/RaftKV/utils"
	"go.uber.org/zap"
)
import "crypto/rand"
import "math/big"

type Clerk struct {
	servers   []*labrpc.ClientEnd
	leaderId  int64
	clientId  int64 // generated by nrand(), it would be better to use some distributed ID generation algorithm that guarantees no conflicts
	commandId int64 // (clientId, commandId) defines a operation uniquely
}

func nrand() int64 {
	max := big.NewInt(int64(1) << 62)
	bigx, _ := rand.Int(rand.Reader, max)
	return bigx.Int64()
}

func MakeClerk(servers []*labrpc.ClientEnd) *Clerk {

	zap.S().Warn(utils.GetCurrentFunctionName())

	clerk := &Clerk{
		servers:   servers,
		leaderId:  0,
		clientId:  0,
		commandId: 0,
	}
	return clerk
}

func (ck *Clerk) Query(num int) Config {

	zap.S().Warn(utils.GetCurrentFunctionName())

	//ShardCtrler.Command
	return ck.Command(&CommandRequest{Num: num, Op: OpQuery})
}

func (ck *Clerk) Join(servers map[int][]string) {

	zap.S().Warn(utils.GetCurrentFunctionName())

	ck.Command(&CommandRequest{Servers: servers, Op: OpJoin})
}

func (ck *Clerk) Leave(gids []int) {

	zap.S().Warn(utils.GetCurrentFunctionName())

	ck.Command(&CommandRequest{GIDs: gids, Op: OpLeave})
}

func (ck *Clerk) Move(shard int, gid int) {

	zap.S().Warn(utils.GetCurrentFunctionName())

	ck.Command(&CommandRequest{Shard: shard, GID: gid, Op: OpMove})
}

func (ck *Clerk) Command(request *CommandRequest) Config {

	zap.S().Warn(utils.GetCurrentFunctionName())

	request.ClientId, request.CommandId = ck.clientId, ck.commandId
	for {
		var response CommandResponse
		//zap.S().Info(zap.Any("key", ck.leaderId))
		if ck.servers[ck.leaderId].Rpc == nil {
			tmp := utils.MakeEnd(ck.servers[ck.leaderId].Endname)
			if tmp == nil {
				return Config{}
			}

			ck.servers[ck.leaderId].Rpc = tmp.Rpc
		}

		err := ck.servers[ck.leaderId].Rpc.Call("ShardCtrler.Command", request, &response)
		if err != nil {
			zap.S().Error(zap.Error(err))
		}

		if response.Err == ErrWrongLeader || response.Err == ErrTimeout {
			zap.S().Warn(zap.Int("err leader = ", int(ck.leaderId)), zap.Any("response", response.Err))
			ck.leaderId = (ck.leaderId + 1) % int64(len(ck.servers))
			continue
		}
		ck.commandId++
		return response.Config
	}
}
