# "shardkv" or "shardctrler" or "client"

role: "shardctrler"

shardkv: [ "shardkv1:9111", "shardkv2:9112", "shardkv3:9113"]
shardctrler: [ "shardctrler1:9331", "shardctrler2:9332", "shardctrler3:9333"]